openapi: 3.0.3
info:
  title: Apni Coaching Server 3.0
  description: |-
    This is a production level code written in typescript.
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://apni-coaching-netlify.app
  contact:
    email: msy8795@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:80/api/v1
tags:
  - name: User Controller
    description: Operations about user
paths:
  /user/login:
    post:
      tags:
        - User Controller
      summary: login user
      description: Route for user to login in the application.
      operationId: loginUser
      requestBody:
        description: Requested user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'          
        '401':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401ErrorResponse'
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - bearerAuth: []
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: Password1!
    
    LoginResponse:
      type: object
      properties:
        userDetails:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
            role:
              type: string
        tokens:
          type: object
          properties:
            access:
              type: object
              properties:
                token:
                  type: string
                expires:
                  type: string
                  format: date-time
            refresh:
              type: object
              properties:
                token:
                  type: string
                expires:
                  type: string
                  format: date-time

    401ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Unauthorized
        error:
          type: string
          description: Incorrect email or password
        
    
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    User:
      description: testing
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".