export const TYPES = {
  BatchRepo: Symbol.for('BatchRepo'),
  ClassRepo: Symbol.for('ClassRepo'),
  DepartmentRepo: Symbol.for('DepartmentRepo'),
  MarksRepo: Symbol.for('MarksRepo'),
  NotificationRepo: Symbol.for('NotificationRepo'),
  PaymentRepo: Symbol.for('PaymentRepo'),
  PostRepo: Symbol.for('PostRepo'),
  StudentRepo: Symbol.for('StudentRepo'),
  TeacherRepo: Symbol.for('TeacherRepo'),
  TestRepo: Symbol.for('TestRepo'),
  TokenRepo: Symbol.for('TokenRepo'),
  UserRepo: Symbol.for('UserRepo'),

  AdminService: Symbol.for('AdminService'),
  BatchService: Symbol.for('BatchService'),
  ClassService: Symbol.for('ClassService'),
  DepartmentService: Symbol.for('DepartmentService'),
  NotificationService: Symbol.for('NotificationService'),
  PostService: Symbol.for('PostService'),
  PaymentService: Symbol.for('PaymentService'),
  StudentService: Symbol.for('StudentService'),
  TeacherService: Symbol.for('TeacherService'),
  TestService: Symbol.for('TestService'),
  TokenService: Symbol.for('TokenService'),
  UserService: Symbol.for('UserService'),
};
